'use strict';

// Brain API (Phase F) — make the self-improving loop VISIBLE and ACTIONABLE.
//
// This surfaces the closed loop the rest of the system already runs:
//   detectors → training_signals → governor → training_patches → self_improvement_log
// plus the memory-hygiene pass. Two human actions live here — the one-click
// apply/reject of a `proposed` patch (the Training Review inbox). Everything else
// is read-only observation: brain stats, the patch queue with evidence, the
// self-improvement timeline, detected signals, and a live SSE of memory activity.
//
// Boundaries honored:
//   • feedback.md proposals are NOT handled here — they stay in the existing
//     Learning "Pending review" tab (one approve path, no double-write). This tab
//     only ever touches `training_patches` (agent .md guardrails).
//   • Apply/reject act on ONE explicit, human-selected patchId — never a bulk
//     auto-patch run. The governor/trainer auto-path stays in the scheduled cycle.

const { Router } = require('express');
const { EventEmitter } = require('events');
const { rateLimit } = require('../middleware/rateLimit');
const db = require('../db');
const agentSync = require('../lib/agentSync');
const { getLatestHygieneReport } = require('../lib/memoryHygiene');

const router = Router();

// ── Brain event bus (drives the Brain tab + cross-page cache invalidation) ────
// Bridges the global agentSync memory events (emitted by the reindex drainer and
// the hygiene pass) plus local patch-review actions into one SSE feed.
const brainEvents = new EventEmitter();
brainEvents.setMaxListeners(50);
for (const ev of ['memory.changed', 'memory.reindexed', 'memory.hygiene']) {
  try {
    agentSync.events.on(ev, (p) => {
      try { brainEvents.emit('memory', { kind: ev.split('.')[1], ...(p || {}) }); } catch { /* best-effort */ }
    });
  } catch { /* agentSync optional */ }
}

// ── Evidence phrasing: "seen 4× across 2 projects" ───────────────────────────
function evidenceLabel(signal) {
  if (!signal) return null;
  const occ = Number(signal.occurrences || 0);
  const projs = Array.isArray(signal.projects) ? signal.projects.filter(Boolean) : [];
  const times = occ ? `seen ${occ}×` : 'seen';
  const where = projs.length ? ` across ${projs.length} project${projs.length === 1 ? '' : 's'}` : '';
  return `${times}${where}`;
}

// Attach the originating signal (evidence + context) to each patch row so the
// Training Review card can show WHY without a second round-trip.
function enrichPatches(patches) {
  const ids = [...new Set(patches.map((p) => p.signalId).filter(Boolean))];
  if (!ids.length) return patches.map((p) => ({ ...p, signal: null, evidenceLabel: null }));
  const byId = new Map();
  // Bounded single fetch, indexed in-memory — cheaper than N getTrainingPatch calls.
  for (const s of db.getTrainingSignals({ limit: 2000 })) byId.set(s.id, s);
  return patches.map((p) => {
    const signal = p.signalId ? byId.get(p.signalId) || null : null;
    return {
      ...p,
      signal: signal && {
        id: signal.id, kind: signal.kind, severity: signal.severity,
        signature: signal.signature, occurrences: signal.occurrences,
        projects: signal.projects, evidence: signal.evidence,
      },
      evidenceLabel: evidenceLabel(signal),
    };
  });
}

// ── GET /api/brain/overview — one fetch for the Brain tab header ─────────────
// Brain stats + memory hygiene/freshness + eval trend + recent timeline.
router.get('/brain/overview', rateLimit('read'), (req, res) => {
  try {
    const stats = db.getBrainStats();

    // Memory hygiene (last persisted pass — regenerated by the scheduled hygiene job).
    const h = getLatestHygieneReport();
    const hygiene = h ? {
      generatedAt: h.generatedAt,
      totalChunks: h.totalChunks,
      freshness: h.freshness || null,
      superseded: h.superseded || 0,
      decayFlaggedRefs: h.decayFlaggedRefs || 0,
      staleCapturedTotal: h.staleCapturedTotal || 0,
      orphans: h.orphans || null,
      recommendations: Array.isArray(h.recommendations) ? h.recommendations : [],
    } : null;

    // Eval trend — last ~30 scores ascending for a sparkline + rolling mean.
    let evalTrend = [], evalMean = null, evalSample = 0;
    try {
      const scores = (db.getEvalScores ? db.getEvalScores({ limit: 60 }) : []) || [];
      const sc = scores.filter((s) => typeof s.overall === 'number');
      evalSample = sc.length;
      if (sc.length) evalMean = +(sc.reduce((a, s) => a + s.overall, 0) / sc.length).toFixed(2);
      evalTrend = sc.slice(0, 30).reverse().map((s) => ({ ts: s.ts, overall: +s.overall.toFixed(2), agent: s.agent || null, caseId: s.caseId || null }));
    } catch { /* eval optional */ }

    const recentTimeline = db.getSelfImprovementLog({ limit: 12 });

    res.json({ stats, hygiene, eval: { trend: evalTrend, mean: evalMean, sample: evalSample }, recentTimeline });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ── GET /api/brain/patches?status=proposed — the Training Review inbox ────────
router.get('/brain/patches', rateLimit('read'), (req, res) => {
  try {
    const status = req.query.status || 'proposed';
    const agent = req.query.agent || undefined;
    const patches = db.getTrainingPatches({ status, agent, limit: 200 });
    res.json({ items: enrichPatches(patches), counts: db.getBrainStats().patches });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ── GET /api/brain/signals?status=open — detected weaknesses (what's "wrong") ─
router.get('/brain/signals', rateLimit('read'), (req, res) => {
  try {
    const signals = db.getTrainingSignals({
      status: req.query.status || undefined,
      agent: req.query.agent || undefined,
      kind: req.query.kind || undefined,
      limit: 200,
    });
    res.json({ items: signals });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ── GET /api/brain/timeline — the self-improvement log (signals→patches→rollbacks) ─
router.get('/brain/timeline', rateLimit('read'), (req, res) => {
  try {
    const limit = Math.min(Number(req.query.limit) || 50, 200);
    res.json({ items: db.getSelfImprovementLog({ kind: req.query.kind || undefined, agent: req.query.agent || undefined, limit }) });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ── Continuity brief (v29) — what the SessionStart hook reads back ────────────
// Render the stored continuity state into a compact "since last time" briefing
// the SessionStart hook injects as additionalContext. Returns '' when there's
// nothing worth surfacing (the hook then prints nothing — never noise).
function renderBriefText(brief) {
  const out = [];
  const idf = brief.identity || [];
  // Identity/prefs that should steer behavior — non-negotiables + preferences first.
  const steer = idf.filter((f) => f.kind === 'non_negotiable' || f.kind === 'preference' || f.kind === 'value');
  if (steer.length) {
    out.push('**How Yash works (locked):**');
    for (const f of steer.slice(0, 8)) out.push(`- [${f.kind}] ${f.statement}`);
  }
  const loops = brief.openLoops || [];
  if (loops.length) {
    out.push('', '**Open loops (unfinished from before):**');
    for (const l of loops.slice(0, 8)) {
      const due = l.dueAt ? ` · due ${l.dueAt.slice(0, 10)}` : '';
      const proj = l.project ? ` (${l.project})` : '';
      out.push(`- ⏳ ${l.title}${proj}${due} — ${l.owner}`);
    }
  }
  const refl = brief.reflections || [];
  if (refl.length) {
    out.push('', '**Recent reflections:**');
    for (const r of refl.slice(0, 5)) out.push(`- ${r.kind}: ${r.summary}`);
  }
  const fb = brief.feedback || [];
  if (fb.length) {
    out.push('', '**Recent corrections:**');
    for (const f of fb.slice(0, 6)) out.push(`- ${f.severity === 'p0' ? '⚠ P0 ' : ''}${f.directive}`);
  }
  if (!out.length) return '';
  return ['## 🧠 Since last time (Polyglot brain)', '', ...out].join('\n');
}

// ── GET /api/brain/session-brief — the "since last time" recall payload ───────
// Consumed by the SessionStart hook (returns text + structured data). Read-only,
// cheap (single pass over the continuity tables). project narrows scope; global
// identity facts are always included.
router.get('/brain/session-brief', rateLimit('read'), (req, res) => {
  try {
    const brief = db.getSessionBrief({ project: req.query.project || null });
    const text = renderBriefText(brief);
    res.json({
      ...brief,
      text,
      counts: {
        identity: (brief.identity || []).length,
        openLoops: (brief.openLoops || []).length,
        reflections: (brief.reflections || []).length,
        feedback: (brief.feedback || []).length,
      },
    });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ── POST /api/brain/patches/:id/apply — human approves a proposed patch ───────
// Runs the SAME surgical writePatch the auto-path uses, then records it as a
// human-approved application and queues a reindex. One explicit patchId only.
router.post('/brain/patches/:id/apply', rateLimit('write'), async (req, res) => {
  try {
    const { applyProposedPatch } = await import('../intelligence/trainer.mjs');
    const r = applyProposedPatch(req.params.id, { by: 'yash' });
    if (!r.ok) return res.status(r.reason === 'no-patch' ? 404 : 409).json({ error: r.reason || 'apply failed' });
    try { brainEvents.emit('patch', { id: req.params.id, status: 'applied' }); } catch { /* ignore */ }
    res.json({ ok: true, id: r.id, alreadyApplied: !!r.alreadyApplied });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ── POST /api/brain/patches/:id/reject — human rejects a proposed patch ───────
router.post('/brain/patches/:id/reject', rateLimit('write'), async (req, res) => {
  try {
    const { rejectProposedPatch } = await import('../intelligence/trainer.mjs');
    const r = rejectProposedPatch(req.params.id, { by: 'yash' });
    if (!r.ok) return res.status(r.reason === 'no-patch' ? 404 : 409).json({ error: r.reason || 'reject failed' });
    try { brainEvents.emit('patch', { id: req.params.id, status: 'rejected' }); } catch { /* ignore */ }
    res.json({ ok: true, id: r.id });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ── Decision journal (v30) — learn from consequences ─────────────────────────
// GET /api/brain/decisions/unresolved — aged decisions still awaiting an outcome,
// plus the rolling decision-accuracy from the ones already resolved. Review-only.
router.get('/brain/decisions/unresolved', rateLimit('read'), (req, res) => {
  try {
    const daysOld = Math.max(0, Number(req.query.daysOld) || 0);
    const project = req.query.project || null;
    const limit = Math.min(Number(req.query.limit) || 50, 500);
    const items = db.getUnresolvedDecisions({ daysOld, project, limit });
    const accuracy = db.getDecisionAccuracy({ sinceDays: Number(req.query.sinceDays) || 90 });
    res.json({ items, accuracy });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// POST /api/brain/decisions/:id/resolve  { outcome:'confirmed'|'wrong', correctnessScore?, note? }
// Records the real-world outcome of one decision (reflections.kind='decision').
// This is the consequence half of the loop — review-only, writes no memory/identity.
router.post('/brain/decisions/:id/resolve', rateLimit('write'), (req, res) => {
  try {
    const { outcome, correctnessScore = null, note = null } = req.body || {};
    if (outcome !== 'confirmed' && outcome !== 'wrong') {
      return res.status(400).json({ error: "outcome must be 'confirmed' or 'wrong'" });
    }
    const r = db.updateReflectionOutcome({ id: req.params.id, outcome, correctnessScore, note });
    if (!r.changed) return res.status(404).json({ error: 'Decision not found or not a pending decision' });
    try { brainEvents.emit('memory', { kind: 'decision-resolved', id: req.params.id, outcome: r.outcome }); } catch { /* ignore */ }
    res.json({ ok: true, id: req.params.id, outcome: r.outcome, correctnessScore: r.correctnessScore });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ── GET /api/brain/stream — SSE: ready / memory / patch ──────────────────────
router.get('/brain/stream', (req, res) => {
  res.set({
    'Content-Type': 'text/event-stream',
    'Cache-Control': 'no-cache, no-transform',
    Connection: 'keep-alive',
    'X-Accel-Buffering': 'no',
  });
  res.flushHeaders?.();

  const send = (type, payload) => {
    res.write(`event: ${type}\n`);
    res.write(`data: ${JSON.stringify(payload)}\n\n`);
  };
  try { send('ready', { proposed: db.getBrainStats().patches.proposed }); } catch { /* ignore */ }

  const onMemory = (p) => send('memory', p);
  const onPatch = (p) => send('patch', p);
  brainEvents.on('memory', onMemory);
  brainEvents.on('patch', onPatch);

  const heartbeat = setInterval(() => { try { res.write(': keepalive\n\n'); } catch { /* closed */ } }, 25_000);
  const cleanup = () => {
    clearInterval(heartbeat);
    brainEvents.off('memory', onMemory);
    brainEvents.off('patch', onPatch);
  };
  req.on('close', cleanup);
  req.on('end', cleanup);
});

module.exports = { router };
