// gate-editability-greps.sh (#3) had NO fixture at all, and three defects surfaced in it this week:
//   · its write_report takes blockers as $2 with warnings hardcoded to [], so a first attempt at an
//     empty-scope N/A warning would have shipped as a false BLOCK on every clean run (QA-7);
//   · it grepped the GENERATED brand cascade for hardcoded colour — the one file whose job is to hold
//     those literals (CB-9);
//   · it flagged `shopify://shop_images/x.png`, which is EXACTLY what the theme editor writes when a
//     merchant picks an image, as a hardcoded URL — 44 of cravinbyandy's 45 findings (CB-9).
//
// All three are false BLOCKS, and a false block is as damaging as a false pass: it trains the team to
// wave the gate through. This pins the real behaviour so the next change cannot re-break it.
//
// The gate is diff-scoped (git diff base...HEAD), so each case builds a real git repo with a `base`
// tag and commits the theme files on top.

import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { spawnSync } from 'node:child_process'
import { fileURLToPath } from 'node:url'

const GATE = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..', 'gate-editability-greps.sh')
let failures = 0
const ok = (m) => console.log('  PASS  ' + m)
const bad = (m) => { console.log('  FAIL  ' + m); failures++ }

// files: { 'assets/x.css': '...' } — committed AFTER the base tag so they are in scope
function run(files) {
  const d = fs.mkdtempSync(path.join(os.tmpdir(), 'edit-'))
  const git = (...a) => spawnSync('git', a, { cwd: d, stdio: ['ignore', 'ignore', 'ignore'] })
  git('init', '-q', '.')
  git('-c', 'user.email=a@b.c', '-c', 'user.name=t', 'commit', '-q', '--allow-empty', '-m', 'base')
  git('tag', 'base')
  for (const [rel, body] of Object.entries(files)) {
    fs.mkdirSync(path.join(d, path.dirname(rel)), { recursive: true })
    fs.writeFileSync(path.join(d, rel), body)
  }
  git('add', '-A')
  git('-c', 'user.email=a@b.c', '-c', 'user.name=t', 'commit', '-q', '-m', 'work')
  const reportDir = path.join(d, 'gate-reports')
  spawnSync('bash', [GATE], { cwd: d, encoding: 'utf-8', env: { ...process.env, REPORT_DIR: reportDir } })
  let rep = null
  try { rep = JSON.parse(fs.readFileSync(path.join(reportDir, 'editability.json'), 'utf-8')) } catch { /* none */ }
  fs.rmSync(d, { recursive: true, force: true })
  return {
    blockers: rep?.blockers || [],
    warnings: rep?.warnings || [],
    pass: rep?.pass,
    ids: new Set((rep?.blockers || []).map((b) => b.id)),
  }
}

console.log('gate-editability — merchant-picked values are not hardcoded URLs')
{
  // the theme editor writes exactly this when a merchant picks an image; flagging it tells the team to
  // "fix" the very thing the gate is asking for
  const r = run({ 'templates/index.json': JSON.stringify({ sections: { hero: { settings: { image: 'shopify://shop_images/1_7.png', mobile_image: 'shopify://shop_images/1_7_1.png' } } } }, null, 2) })
  r.ids.has('editability.1.2') ? bad(`shopify:// flagged as a hardcoded URL: ${r.blockers.length}`) : ok('shopify:// image references are not flagged')
}
{
  // ...and a genuinely hardcoded CDN image in a stylesheet must STILL block, or the exclusion above
  // would have gutted the check
  const r = run({ 'assets/section-x.css': '.x { background: url(https://cdn.shopify.com/s/files/1/0883/files/Frame_2147240171.png?v=1784781495); }' })
  r.ids.has('editability.1.2') ? ok('a hardcoded CDN image url() still blocks') : bad('the real hardcoded URL is no longer caught')
}

console.log('\n── generated files are not hand-authored ──')
{
  const gen = '/* GENERATED by generate-design-system-css.mjs from docs/design/design-system.json — do not edit by hand. */\n:root { --ds-color-x: #C8102E; }\n'
  const r = run({ 'assets/design-system.css': gen })
  r.blockers.length === 0 ? ok('the generated brand cascade is skipped') : bad(`generated file flagged: ${[...r.ids].join(', ')}`)

  // the same body WITHOUT the header is hand-authored and must still be checked
  const r2 = run({ 'assets/hand.css': ':root { --ds-color-x: #C8102E; }\n' })
  r2.blockers.length > 0 ? ok('the same content hand-authored still blocks') : bad('the generated-skip leaked to hand-authored files')
}

console.log('\n── the checks still bite on real defects ──')
{
  const r = run({ 'sections/promo.liquid': '<div class="promo"><h2>Book your catering today</h2><p>We cater weddings and parties across the city.</p></div>\n' })
  r.ids.has('editability.1.1') ? ok('hardcoded English in render output blocks') : bad(`got [${[...r.ids].join(', ')}]`)
}

console.log('\n── an empty scope declares itself (QA-7) ──')
{
  // nothing changed vs base: the gate must PASS, say so via an *.n-a-* warning, and — the bug that was
  // caught before it shipped — must NOT put that warning in the blockers slot
  const r = run({})
  const naOk = r.pass === true && r.blockers.length === 0 && r.warnings.some((w) => /\.n-a-/.test(w.id || ''))
  naOk ? ok('empty scope → pass, 0 blockers, N/A warning in the WARNINGS slot')
    : bad(`pass=${r.pass} blockers=${r.blockers.length} warnings=${JSON.stringify(r.warnings.map((w) => w.id))}`)
}

console.log(failures === 0 ? '\neditability: ALL CASES PASS' : `\neditability: ${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
