// audit-ownership — "whose fault is this finding?" (the third sibling audit).
//
// It exists because the SAME defect shape was found six separate times in one week, every one by
// accident, and every one a FALSE BLOCK:
//   stock Dawn dragged into a drift scan (CB-10) · stock Dawn's type vocabulary counted as ours (CB-11)
//   the generated cascade flagged for holding the literals it exists to hold (CB-9)
//   `shopify://shop_images/x.png` — a merchant's own image pick — read as a hardcoded URL (CB-9)
//   our vendored test fixture's fake private key read as the client's secret (CB-9)
//   `| times: 0.75` read as money (CB-12)
// A false block is as damaging as a false pass: it teaches the team to wave the gate through.
//
// The two things that must hold for the audit to mean anything: the classifier has to put each file in
// the right bucket, and the ALLOWED map must not be able to swallow a genuine misattribution.

import fs from 'node:fs'
import { classify, ALLOWED, buildFixtureTheme } from '../../audit-ownership.mjs'

let failures = 0
const ok = (m) => console.log('  PASS  ' + m)
const bad = (m) => { console.log('  FAIL  ' + m); failures++ }
const CWD = '/repo'

console.log('classify — the six shapes that actually bit us')
{
  const cases = [
    ['assets/base.css', 'theme-base', 'stock Dawn (CB-10/CB-11)'],
    ['assets/component-cart.css', 'theme-base', 'stock Dawn component'],
    ['assets/design-system.css', 'generated', 'the brand cascade (CB-9)'],
    ['templates/index.json', 'merchant-data', 'merchant section picks (CB-9)'],
    ['config/settings_data.json', 'merchant-data', 'merchant theme settings'],
    ['toolkit/scripts/__fixtures__/x/run-tests.mjs', 'vendored', 'our own test data (CB-9)'],
    ['assets/section-hero.css', 'ours', 'a section we wrote'],
    ['sections/hero.liquid', 'ours', 'a section we wrote'],
  ]
  let wrong = 0
  for (const [p, want, why] of cases) {
    const got = classify(`${CWD}/${p}`, CWD)
    if (got !== want) { bad(`${p} → ${got}, expected ${want} (${why})`); wrong++ }
  }
  wrong === 0 ? ok(`all ${cases.length} ownership shapes classify correctly`) : bad(`${wrong} misclassified`)

  // an absolute path is what gates actually report; a bare relative one must work too
  classify('assets/base.css', CWD) === 'theme-base' ? ok('a relative page path classifies the same') : bad('relative path mishandled')
  classify('', CWD) === 'other' && classify(undefined, CWD) === 'other'
    ? ok('an empty/absent page is "other", never mistaken for ours') : bad('empty page mishandled')
}

console.log('\n── the ALLOWED map must be a claim, not an escape hatch ──')
{
  // every entry names a gate whose remit genuinely includes that class
  const entries = [...ALLOWED.entries()]
  entries.length > 0 && entries.every(([, set]) => set.size > 0)
    ? ok(`${entries.length} allowlisted gate(s), each with at least one class`) : bad('ALLOWED is malformed')

  // NOTHING may be allowed against 'theme-base': that is the CB-10/CB-11 class, and it is never the
  // team's fault. If a future entry adds it, this fails loudly.
  const baseLeak = entries.filter(([, set]) => set.has('theme-base')).map(([g]) => g)
  baseLeak.length === 0
    ? ok('no gate is allowed to blame stock theme-base code') : bad(`theme-base allowlisted for: ${baseLeak.join(', ')}`)

  // and the allowlist must not cover 'ours' — that would silence the control
  const oursLeak = entries.filter(([, set]) => set.has('ours')).map(([g]) => g)
  oursLeak.length === 0 ? ok("no gate is allowed to skip OUR code") : bad(`ours allowlisted for: ${oursLeak.join(', ')}`)
}

console.log('\n── the fixture theme really does contain one dirty file per class ──')
{
  const d = buildFixtureTheme()
  const has = (p) => fs.existsSync(`${d}/${p}`)
  has('assets/base.css') && has('assets/design-system.css') && has('templates/index.json')
    && has('config/settings_data.json') && has('toolkit/scripts/__fixtures__/secret-probe/run-tests.mjs')
    && has('sections/ours.liquid')
    ? ok('every ownership class is represented') : bad('the fixture theme is incomplete')

  // the generated file must look like real generator output — a :root block and nothing else.
  // An earlier draft appended a normal CSS rule to it, which INVENTED two misattributions that were
  // artefacts of the fixture rather than defects in the gates.
  const gen = fs.readFileSync(`${d}/assets/design-system.css`, 'utf-8')
  const hasHeader = /GENERATED by/
  const hasRule = /^\s*\.[a-z]/mi
  hasHeader.test(gen) && !hasRule.test(gen)
    ? ok('the generated cascade is realistic (:root tokens only, no authored rules)') : bad('the fixture cascade is not realistic')

  // the base tag must exist, or every gate silently skips and "0 misattributed" is vacuous
  fs.existsSync(`${d}/.git/refs/tags/base`) ? ok('a `base` tag exists so scope resolves') : bad('no base tag — the audit would be vacuous')
  fs.rmSync(d, { recursive: true, force: true })
}

console.log(failures === 0 ? '\nownership: ALL CASES PASS' : `\nownership: ${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
